local Components = {}

Components.WorldMapOrchestrator = require(script.WorldMapOrchestrator)
Components.DungeonOrchestrator = require(script.DungeonOrchestrator)
Components.InventoryNode = require(script.Pipeline.InventoryNode)
Components.SplinePlannerNode = require(script.Pipeline.SplinePlannerNode)
Components.BlockoutNode = require(script.Pipeline.BlockoutNode)
Components.TerrainPainterNode = require(script.Pipeline.TerrainPainterNode)
Components.RockScatterNode = require(script.Pipeline.RockScatterNode)
Components.MountainRoomPlacer = require(script.Pipeline.MountainRoomPlacer)
Components.MiniMap = require(script.MiniMap)

-- Room geometry pipeline
Components.RoomMasser     = require(script.Pipeline.RoomMasser)
Components.ShellBuilder   = require(script.Pipeline.ShellBuilder)
Components.DoorPlanner    = require(script.Pipeline.DoorPlanner)
Components.TrussBuilder   = require(script.Pipeline.TrussBuilder)
Components.LightBuilder   = require(script.Pipeline.LightBuilder)
Components.PadBuilder     = require(script.Pipeline.PadBuilder)
Components.SpawnSetter    = require(script.Pipeline.SpawnSetter)
Components.Materializer   = require(script.Pipeline.Materializer)
Components.DoorCutter     = require(script.Pipeline.DoorCutter)
Components.MountainBuilder = require(script.Pipeline.MountainBuilder)
Components.MountainRoomMasser = require(script.Pipeline.MountainRoomMasser)
Components.MountainTerrainPainter = require(script.Pipeline.MountainTerrainPainter)
Components.MountainLightBuilder = require(script.Pipeline.MountainLightBuilder)
Components.FeaturePlacer = require(script.Pipeline.FeaturePlacer)
Components.ChunkManager = require(script.Pipeline.ChunkManager)
Components.WaterFloodNode = require(script.Pipeline.WaterFloodNode)
Components.SandPainterNode = require(script.Pipeline.SandPainterNode)
Components.ShoreCutterNode = require(script.Pipeline.ShoreCutterNode)
Components.TerrainPainter = require(script.Pipeline.TerrainPainter)
Components.IceTerrainPainter = require(script.Pipeline.IceTerrainPainter)
Components.PortalBlender      = require(script.Pipeline.PortalBlender)
Components.PortalRoomBuilder  = require(script.Pipeline.PortalRoomBuilder)
Components.PortalTrigger   = require(script.PortalTrigger)
Components.PortalCountdown = require(script.PortalCountdown)

return Components
