--[[
    LichterveldeGreybox
    Generated by GeometrySpec Scanner
    Apply classes and fine-tune as needed

    Cathedral is referenced from LichterveldeCathedral.lua
--]]

-- Cathedral position within the greybox
local CATHEDRAL_POSITION = {-4, 0, 20}
local CATHEDRAL_Y_OFFSET = 0  -- Y offset now baked into cathedral layout

return {
    name = "LichterveldeGreybox",

    spec = {
        origin = "floor-center",
        bounds = {1000, 200, 1000},  -- Large enough to contain the village

        parts = {
            {
                id = "Ground",
                position = {4, -1, 4},
                size = {1000, 2, 1000},
                Color = {255, 255, 255},
                Material = "Cobblestone",
            },
            {
                id = "Bldg_S1",
                position = {149, 18, 347},
                size = {90, 36, 62},
                rotation = {0, 3, 0},
                Color = {195, 190, 180},
                Material = "SmoothPlastic",
            },
            --[[
                Cathedral reference - replaces greybox volumes
                The cathedral's floor-center origin aligns with this position
                Front facade (tower) faces negative Z (toward Bldg_NE area)
                Y offset raises it to sit on grass mound
            --]]
            {
                id = "Cathedral",
                ref = "LichterveldeCathedral",
                position = {CATHEDRAL_POSITION[1], CATHEDRAL_POSITION[2] + CATHEDRAL_Y_OFFSET, CATHEDRAL_POSITION[3]},
                rotation = {0, 0, 0},
            },
            {
                id = "Bldg_W4",
                position = {-197, 18, -97},
                size = {64, 36, 116},
                rotation = {0, 70, 0},
                Color = {200, 195, 185},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_W3",
                position = {-188, 18, -17},
                size = {70, 36, 62},
                rotation = {0, 82, 0},
                Color = {195, 190, 180},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_W2",
                position = {-193, 18, 49},
                size = {55, 36, 60},
                rotation = {0, 88, 0},
                Color = {190, 185, 175},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_S3",
                position = {-72, 18, 369},
                size = {58, 36, 122},
                rotation = {0, -3, 0},
                Color = {200, 195, 185},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_SW2",
                position = {-184, 18, 166},
                size = {58, 36, 62},
                rotation = {0, -85, 0},
                Color = {195, 190, 180},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_SW1",
                position = {-185, 18, 226},
                size = {60, 36, 65},
                rotation = {0, -92, 0},
                Color = {190, 185, 175},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_S2",
                position = {-8, 18, 345},
                size = {60, 36, 65},
                Color = {185, 180, 170},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_W1",
                position = {-202, 18, 107},
                size = {58, 36, 62},
                rotation = {0, -88, 0},
                Color = {185, 180, 170},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_N_L1",
                position = {-58, 18, -247},
                size = {55, 36, 60},
                Color = {195, 190, 180},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_N_L2",
                position = {-124, 18, -217},
                size = {88, 36, 65},
                rotation = {0, -5, 0},
                Color = {190, 185, 175},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_SE2",
                position = {231, 18, 263},
                size = {92, 36, 65},
                rotation = {0, 87, 0},
                Color = {190, 185, 175},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_E2",
                ref = "Shop1",
                position = {193, 0, 40},
                rotation = {0, -90, 0},
                styles = {
                    roof = { Color = {60, 80, 120} },  -- Blue-gray roof
                    floor_upper = { Color = {220, 215, 200} },
                },
            },
            {
                id = "Bldg_E3",
                position = {194, 18, 111},
                size = {65, 36, 70},
                rotation = {0, 92, 0},
                Color = {185, 180, 170},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_NE2",
                position = {94, 18, -181},
                size = {96, 36, 65},
                rotation = {0, -33, 0},
                Color = {190, 185, 175},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_NE3",
                position = {163, 18, -117},
                size = {65, 36, 70},
                rotation = {0, -58, 0},
                Color = {185, 180, 170},
                Material = "SmoothPlastic",
            },
            {
                id = "Bldg_NE4",
                position = {187, 18, -35},
                size = {70, 36, 62},
                rotation = {0, -85, 0},
                Color = {200, 195, 185},
                Material = "SmoothPlastic",
            },
        },
    },
}
